### ISSUE TITLE
Add Scientific Linux

### ISSUE THREAD

**Issue by opoplawski** [xsuchy/distribution-gpg-keys#2]
Please add Scientific Linux gpg keys.

**Comment by xsuchy** [comment]
Are they somewhere available on one pile? I am able only to find http://ftp.scientificlinux.org/linux/scientific/5x/x86_64/RPM-GPG-KEYs/ and in all other directories. I am not sure which one is used for what.

**Comment by xsuchy** [comment]
I am closing this. If there is some reliable source for those keys then please reopen
