### ISSUE TITLE
RPMFusion symlinks for 33/34 do not exist

### ISSUE THREAD

**Issue by mooninite** [xsuchy/distribution-gpg-keys#39]
I was trying to build a package in mock targeting RPMFusion Free for Fedora 33. RPM was looking for the file:

/usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-free-fedora-33

After creating the symlink RPM was happy and the mock build succeeded. Looks like the one for 34 (Rawhide) is missing, too.

**Comment by xsuchy** [comment]
Thank you for the report.
