### ISSUE TITLE
GPG Key for COPR philfry/gajim missing?

### ISSUE THREAD

**Issue by wurstsemmel** [xsuchy/distribution-gpg-keys#40]
Dear Developers,

I cannot find the GPG Key for the COPR Repository [philfry/gajim](https://copr.fedorainfracloud.org/coprs/philfry/gajim/) in the package `distribution-gpg-keys-copr`.

Please check why it is not included. Thank you!

System: Fedora 33

$ rpm -q distribution-gpg-keys-copr
distribution-gpg-keys-copr-1.44-1.fc33.noarch

**Comment by xsuchy** [comment]
That is because the last release happened in the middle of October and your project was created later.
The keys are not in sync and there is always a few weeks delay. 

I done a release now.

**Comment by wurstsemmel** [comment]
Thank you for your quick reply and your time.
