### ISSUE TITLE
Need keys for the 64-bit ARM (AArch64) architecture

### ISSUE THREAD

**Issue by damarlin** [xsuchy/distribution-gpg-keys#5]
There is now a CentOS-7 release for AArch64:

   http://mirror.centos.org/altarch/7/os/aarch64/

and AArch64 is included in the EPEL7 build, i.e.:

   http://koji.fedoraproject.org/koji/buildinfo?buildID=806342

but I do not find any distribution-gpg-keys for AArch64.

If AArch64 does not use the same keys as x86_64, we need keys for (at a minumum) CentOS-7 (AltArch-7?) and EPEL7.

**Comment by xsuchy** [comment]
Fixed in commit 8315cb2
