### ISSUE TITLE
please add koozali smeserver keys

### ISSUE THREAD

**Issue by unnilennium** [xsuchy/distribution-gpg-keys#74]
you can find them on their mirrors 

http://mirror.canada.pialasse.com/releases/10/smeos/x86_64/

legacy one is for versions prior to SME 10
http://mirror.canada.pialasse.com/releases/10/smeos/x86_64/RPM-GPG-KEY-SMEServer

the one current to SME 10

http://mirror.canada.pialasse.com/releases/10/smeos/x86_64/RPM-GPG-KEY-koozali

for informations about Koozali SME Server

https://wiki.koozali.org/Main_Page

for an alternate mirror

https://mirror.koozali.org/mirrors/

Project is about smeserver, formerly known under e-smith server. It has been hosted for long under contribs.org domain and is under the responsibility of Koozali Foundation now. 

While storing it under **smeserver** seems more appropriate, you could opt for the historical one **contribs** or the one related to the foundation hosting it **koozali** but i would suggest the name of the project : smeserver.

**Comment by xsuchy** [comment]
Added in commit 32b0cd92
