### ISSUE TITLE
Consider renaming the project to avoid a vendor-specific implementation name

### ISSUE THREAD

**Issue by guillemj** [xsuchy/distribution-gpg-keys#76]
Hi!

I realize this might be one of those annoying requests… :) more so given the apparent longevity of the project. But it would be really nice if the project name and other internal references could be switched from gpg (which is a program from the specific GnuPG implementation) to openpgp (which is the IETF OpenPGP RFC4880), or pgp when openpgp is not appropriate or too long (say for filename extensions). I'm aware that GnuPG is currently probably the most predominant implementation, but there are many other implementations that are in a position to displace it, and it would be nice to call things as neutrally as possible to in addition of being more correct, to avoid the potentially perceived impression of lock in that can place an undue burden into those other alternatives. :)

Thanks,
Guillem

**Comment by xsuchy** [comment]
This is hard. GPG is a well-known name. The same as you say "Mastodon" instead of "ActivityPub-based servers". Or you may say Xerox instead of a copy machine. Or lux instead of vacuum-cleaner.

While it is not the correct name per se, everybody is using it.

If you convince the DNF team to change "gpgkey" option in `dnf.conf` to `pgpkey` then I will rename this project.

**Comment by calestyo** [comment]
Just for the record... right now it seems as if GPG will actually break with the next version of OpenPGP... so in the future: GPG may very well no longer be OpenPGP (compatible - except for old versions).

**Comment by calestyo** [comment]
btw: a better idea for renaming would have been IMO something standard-agnostic: e.g. `distribution-keys` or `distribution-crypto-keys` or `distribution-archive-keys` or something like that.

IIRC, Debian itself considers switching away from OpenPGP to something simpler on the long term. OpenBSD uses `signify`.

**Comment by guillemj** [comment]
Ah, something else about the name, perhaps "distribution" should also be made plural, otherwise it reads as it is the package for the current distribution, which might not make sense for example in Debian or other projects for which this project does not ship certificates for.
