### ISSUE TITLE
Update VirtualBox GPG key

### ISSUE THREAD

**Issue by vgaetera** [xsuchy/distribution-gpg-keys#90]
Please update the VirtualBox GPG key.

The new key:
https://www.virtualbox.org/download/oracle_vbox_2016.asc

The repo file using the new key as a proof:
https://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo

**Comment by xsuchy** [comment]
Thank you for the report. I added the new one in parallel to the old one.
